# .github/workflows/verify-build.yml
name: Verify Yocto build (PR → main)

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

# Ensure only one Yocto build runs at a time on this host
concurrency:
  group: yocto-bbb
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 600  # adjust for your build time

    env:
      YOCTO_TOP: /home/zk47/Learning/yocto-bbb
      LAYER_DIR: /home/zk47/Learning/yocto-bbb/meta-bbb
      BUILD_DIR: /home/zk47/Learning/yocto-bbb/build-bbb
      LOG_DIR: /srv/ci-logs/meta-bbb
      LOG_FILE: /srv/ci-logs/meta-bbb/${{ github.run_id }}-${{ github.run_attempt }}.log
      BBSERVER: ""

    steps:
      # Check out the PR's exact commit into the Actions workspace
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Ensure log dir exists
        run: mkdir -p "$LOG_DIR"

      # Sync the PR code into your *local* meta-bbb layer used by Yocto
      # We exclude .git so we don't break your local repo
      - name: Sync layer into local Yocto tree
        run: |
          rsync -a --delete --exclude '.git' "$GITHUB_WORKSPACE/" "$LAYER_DIR/"
          echo "meta-bbb now at: $(git -C "$LAYER_DIR" rev-parse --short HEAD || echo 'workspace copy (no .git changes)')"

      - name: Build image
        shell: bash
        run: |
          set -eo pipefail
          {
            echo "==== $(date -Is) ===="
            echo "Repo: ${{ github.repository }}"
            echo "PR: #${{ github.event.pull_request.number }} (${{ github.head_ref }} -> ${{ github.base_ref }})"
            echo "Runner: $RUNNER_NAME ($RUNNER_OS/$RUNNER_ARCH) on $(hostname)"
            echo "Using YOCTO_TOP=$YOCTO_TOP BUILD_DIR=$BUILD_DIR LAYER_DIR=$LAYER_DIR"
            echo "----- bitbake start -----"

            cd "$YOCTO_TOP"

            # Avoid nounset breakage inside Poky env scripts
            set +u
            # Predefine commonly-probed vars so test expressions don't explode
            : "${ZSH_NAME:=}"
            : "${BBSERVER:=}"
            # IMPORTANT: must *source* the env script (do NOT run with sh/bash)
            . "$YOCTO_TOP/poky/oe-init-build-env" "$BUILD_DIR"
            set -u

            bitbake --version
            bitbake custom-image
            echo "----- bitbake end -----"
          } 2>&1 | tee -a "$LOG_FILE"

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: yocto-build-log-${{ github.run_id }}
          path: ${{ env.LOG_FILE }}

      # Cleanly restore local layer to main so the next build starts from a known state
      - name: Restore meta-bbb to main
        if: always()
        run: |
          cd "$LAYER_DIR"
          if [ -d .git ]; then
            git fetch origin
            git reset --hard origin/main
            git clean -fdx
          fi
